server:
  port: 8080
spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: backendReservaciones
  datasource:
    password: 123
    url: jdbc:mysql://localhost:3307/restaurant_reservations_dev
    username: root
  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: mysql
  jackson:
    time-zone: America/Mexico_City

---
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: backendReservaciones
  datasource:
    password: 123
    url: jdbc:mysql://localhost:3307/restaurant_reservations_prod
    username: root
  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: mysql
  jackson:
    time-zone: America/Mexico_City